<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Yoruba_LibController extends Controller
{
    static function library()
    {
        $hate_words = [
"were",
"werey",
"tidarun ni",
"oloshi",
"oloriburuku",
"omo ale",
"wahala baba yi",
"wahala bobo yi",
"omo jatijati",
"jatijati",
"Tu tu nii",
"Oloju nla",
"ti ko riran",
"buruku",
"agba ya",
"jade",
"o ko ni gba ori",
"o ko ni oye",
"pa",
"mumu",
"itiju",
"ewure",
"agboro",
"agbero",
"omo ale",
"wahalla ju",
"iya re",
"baba yin",
"jiya",
"wahala",
"asewo",
"ole",
"obo",
"obun",
"o leko",
"o gbon",
"alai",
"oni ijongbon",
"jekuje",
"onijekuje",
"arun",
"oponu",
"opolo kukuru",
"onijamba",
"oni ",
"odale",
"rede rede",
"elebi",
"agbaya",
"adigunjale",
"ologogoro",
"omo tinrin",
"alabukun",
"onijibiti",
"o lu jibiti",
"alagana",
"alakogbagbe",
"oni idoti",
"onidoti",
"omo kekere",
"baba kekere",
"ko riran",
"ko leko",
"elemekemi",
"bi elede",
"dindinrin omo",
"dindinrin ni",
"dindinrin",
"oburuku",
"ala tenuje",
"alailojuti",
"oni jamba",
"dindinrin agba",
"alagabagebe",
"alakori",
"oloju kokoro",
"olopolo dudu",
"ika omo",
"ika",
"elenu razo",
"elenu rirun",
"elenu gboro",
"oniwa",
"eranko ni",
"mago mago",
"magomago",
"omuti",
"oni sekuse",
"sekuse",
"apayan",
"oloro",
"arekereke",
"amugbo",
"omo erun",
"oni baje",
"bori ma bowa",
"alai moko",
"olofofo",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alakoba",
"alai leko",
"omo aja",
"won tilee jade nile kuro omoale buruku nii",
"se ori ran ni abi ori e tidarun ni",
"o lo jale nilekeji omo ofo jatijati ",

"were lo poju ninu yin",
"were ni bobo yi sa olofun omo obirin yen loyun ",
"omo ale yoruba ni ki bowo fagba",
"omo lasan ikeji aja",
"awon ajinigbe wonyi eranko ni won o",
"wahala baba yi ti poju bayi o kilode gan",
"ti poju bayi o kilode gan",
"ti poju bayi",
"ogogoroti yi eleyi lori o ojutifo danu",
"Bawolose jeun bi obo bayi ",
"afi ekun lo mon sun wo ori e bi ijoko keke",
"Wo bi ose gbin bi eni to fe bimo kuro lona funmi",
"ewo beleyi se npariwo o ngbo bi aja",
"se o sare ni ti oun mi bi rakunmi",
"oni ikun nla bi eni ti o ni arun kwashiorkor",
"Arun warapa danmu eni wobosese kirii",
"pelu gbogbo iwa yi o ni eko Ile rara",
"ewo ese tinrin bi opa ireke",
"won kukufe kaka iwemo ni orile edewa yi awonoloriburuku gbogbo",
"eyin re fonka oga",
"aiye akamora ika lokunrin yi oo",
"fun ogbon odun oshi nko ise Oponu",
"Ooo siga fifa di ounje we re okunrin",
"O ti e le ronu rara bi nkan se nlo ti ko se dede",
"Oti e ronu rara ni wasamase jakujaku bi eniti kolopolo",
"Kilode ti oun da soro bi we re",
"kilo de tole bere mole iwo omo ole lasan yi",
"Orun padi o un duro de o ti o ko ba yipada ninu iwa buruku yi",
"Alainironu oun na owo bi pe kosi ola",
"Aso baba re ni iwo nwo alailojuti",
"Ewo bi ose baje Olorun yio ko ee",
"Won ma ko e sile nisin pelu iwa idoti ti o unhu yen",
"Olowo o de gba ayo oti e ni ironu rara",
"Ole ko ole ka Olodo",
"Onijibiti obirin osaya gbangban",
"Ounpe ara re ni akeke nitori oro to wa ninu re",
"eleyi ti bo ojola re danu",
"pelu gbogbo atike ko si ore okunrin Ewo idi Pelebe bi kpako",
"baba kukuru bi tinubu Okuru bi odo",
"okan ri rederede ode",
"oun jeun bi elebi",
"isoro idile re ti poju olorun lo le ba yin tan",
"emi ni mo ma pa iya re",
"oun sin bi alarun covid",
"Oko meta kotoo oni sinan obirin ",
"O lopolo ode nii ee",
"ode nii ee",
"ode",
"Oni Ori nla ode lopolo",
"Oloju nla ti ko riran",
"Ikani gbogbo awon oselu won yi jee",
"Gbogbo nkan ti opolo re ro suya ni omo hausa",
"eji re dabi ferese ti won si kale",
"oa joko bi eniti ko niran ",
"ogoji odun okurin ti ko ni ironu",
"gbogbo aso re ni okirika oruko re apada di okiri ka",
"arun kokoro tetanus wa ni opolo are wa",
"omo okurin yi ori ranmo oo selo dabi ojue tifo ",
"dwon oko oloribu lo kunun ita nsin",
"Bolanle shorun gigun bi rakunmi ",
"Oti ma soro ju osebi eye aiye koto",
"Oro re ti su esu funrarare",
"Ori re bi Ile akoku",
"Ewo eti bi eti ehoro",
"oti dudu ju bi ikoko isasun abule",
"Moma mu eran saju re iwo alaidaa yi",
"oun mumi bi aja farabale na",
"Ijakule lo Kun opolo re",
"Ara omobirin yen sa run bi eniti ofi iru wesun",
"Eranko gbaa ni awon fulani won yi ",
"omo re dabi bebi alosho ",
"irun abiya bi ti Inu igbo",
"ewo oju re bi ti were",
"adugbo re dabi ti were",
"adugbo Ile re dabi ite oku",
"ori re nyi bi shiarin oko",
"ole gba eyan ni iyanju rara",
"o le ni ironu mo pelu gbogbo eko ti won ko e",
"omo ode le bi o pelu iwa ago to wu",
"ode ma si eyin sile bi eyin were",
"olori buruku eni ti Olorun ma se idajo fun",
"dindinrin ni omo ti eran nise lo si oja",
"Olorun bi orun adiye se o kin we ni",
"obun elede leleyi wo bi gbogbo ara re se nrun",
"o ko ni eko Ile rara pelu iwa alainironu to hu yen",
"o ko lati ko eko pelu ile iwe giga ti o nlo",
"Iranu osi ni ibere ti o bere yi",
"oburu ju aje lo ni omo ti e un wo yen",
"olori buruku eda ni awon to ungbe adugbo yi o",
"oni se orire laye pelu gbogbo iwa asoni lenu ti o un wu ",
"Bi iya re kose jere mama re Iwo na koni jere omo re",
"Amukun eru re wo o ni oke le now e o wo isale",
"se oti e ko eko rara olodo omo kekere",
"ole alapa ma se ise ole se ise amon ole jeun",
"omo oju ko ri ola ri to so omo re ni ola ni iyonu",
"awon omo Inu re ni wa ma sise fun",
"orire o pe pelu oro isokuso ti o so lenu ",
"won ti paro ogo re ni gbogbo re fi daru fun be yen",
"ko bada ko tete ri ogo re ti osonu ko le vri ona lo",
"mo korira gbogbo nkan nipa awon ara ilu odi keji ",
"o ni jamba eniyan ni okunrin to unbo lokan ",
"ibi lo ma ku si ko si un kan to le se si",
"ounje lo ma pa e iwo onijekuje omo",
"Ogbon jamba ti poju lowo e",
"o fe gba mii oloribu alainironu",
"iyawo obun Kun ori Facebook ",
"enu re ti nrun ju kora e jade kuro ni iwaju mi",
"didirin re po ",
"alailojuti ni iwo omo obinrin to unja nibe yen",
"oti ta ojo iwaju re",
"awon oponu ori le ede yi lo unse ilu basubasu",
"Habaah ala tenuje lo brin saa",
"Ilorin mesu jamba",
"Koni da fun e ati awon to ran e wa sibi lati wa da wahala sile",
"oju a pada ti e ati awon ti e jo parapo lati wa se ise ibi nibiyi",
"imu e dabi iderii koko",
"wo bi irungbon e se ri bi koinkoin",
"ode iya lo ma pe mi ",
"ode okunrin ni e wo bi omo kekere se lo ogbon fun e",
"koseni to go to e o go o fi enu ho ara",
"Alagabagebe obinrin ni omo to gbe ise wa",
"alailojuti omuti o mo wipe won se ise leni",
"Alagabagebe okunrin ni oga to won gbe wa sile iwe wa ",
"ewo ekana bi ti asa",
"awon obirin ti ni ojukokoro ju opolopo won ni won ko ni itelorun",
"awon omo isin yi ti daju ju won o beru nkan to ma sele",
"omo yen ko kin se algabagebe ",
"oju re bi itana gbogbo nkan ni o ma nri ",
"emi ko kin se alagabagebe eniyan bo ba se ri ni mo ma so",
"awon alaimokan ijoba wa ndoju timi",
"odabi pe were ndamu re lo se nse jatijati",
"awon okunrin mi buru ju esu lo won o se gbekele lo titi",
"ode ni omo ti e ran nise o ti gbe owo sonu",
"ko si ode ninu wa nibi gbogbo wa la ja fafa",
"obirin loma pa e ati pupa si dudu si giga si kukuru gbogbo e lo ma un wun e",
"Koni da fun awon eniyan re ati awon to ba e wa",
"se mo fi oju jo ode ni to fi wa lo ogbon yen funmi",
"nkan ti ndamu opolo e lo je ki o ma wuwa rederede",
"were gidi niwon walai",
"Awon to gbe egbira gun keke lo je ki eranko yi ma lago leyan lori o",
"Awon asiwere nikan ni o ni idotin pelu eniyan ti o je nikan pelu ounje won",
"O ko le se atunse omugo nitorina ti o ba je asiwere daradara o gba iye ti osu kan ti awo didan didan",
"Asewo ti ko lojuti ni omoobinrin yi bo se si idi sile",
"obirin tio mo bi won se padimon asa joko jakajaka",
"Onije wobia yi",
"Alailanu okunrin ama seka fun iyawo e",
"Were alaso kuku niyin",
"Alai lanu eniyan",
"oti fi gbogbo owo mu oti ko lakojo",
"oponu ayerada to fi omo sogun owo",
"dindirin oko afi ko mu oti",
"dindirin iyawo afi ko mu oti",
"dindirin omo afi ko sere",
"dindirin omo afi ko gba bolu",
"dindirin iyawo afi ko jeun",
"dindirin oko afi ko jeun",
"dindirin omo afi ko jeun",
"dindirin omo afi ko sun",
"Oju e bi oju agbenipa",
"dindirin iyawo afi ko na owo oko ni inakuna",
"dindirin oko afi ko yeye iyawo e loju gbogbo aye",
"iyawo olobun ti o kin we",
"oko olobun ti o kin we",
"omo oni sekuseyi gbogbo okunrin lobaasun ",
"oloju kokoro iyawo ti o ni itelorun",
"oni pata gi gan",
"ode oko to unlu iyawo ni e",
"ode oko toun yeye iyawo ni e",
"ode iyawo ti o kin toju ile",
"ode iyawo ti o mo ara mu",
"ode iyawo ti o mo ara mu",
"ode iyawo ti o onje se",
"ode iyawo ti o le tunju omo",
"Alabukun eniyan ni ore to unmo lokan yen",
"apayan obinrin",
"apayan okunrin",
"ewure oshi ti ko gboro soko lenu",
"ewure oshi ti ko gboro sobi lenu",
"ode o se Ori bi igun ile",
"Omo elenu raso lomo ile keji",
"o jo asiwere pupo",
"Ki a pa iwo ati awon ore atata re ti o kupo e ko to unkankan ni opopona yi",
"won sope olosho ni omo yen mi o tete mope ise ashewo lo unshe",
"igbo lo ma kusi o ni kusiti eru e wa",
"omo lasan ikeji aja",
"apaniyan ni omo to se oju koko bi oju odaran yi o",
"oniwahala aye ati ti orun ni e igba gbogbo ni o ma unfa wahala",
"Isoro si e ri bi ti afipabanilopo ",
"Iwa ifipabanilopo wa lowo awon omo agbegbe yi",
"iwa eleyameya lo unhu yen o",
"onisokuso ni awon ara ile wa ko si oro ti won kole so siyan",
"ti e ba ti lo ara yin ni ilokulo e mama wa dogbo bi pe angeli niyin",
"Awon onijagidijagan ni omo ilewa ko si eni ti ko mo won",
"onisekuse ni awon omo isin won o le muara duro",
"alagabagebe ni eni ti a fi oro wa lenu wo ko loto kankan",
"ipanilaya ati ifipabanilopo ni ounkan ti awon boko haram ma unse",
"ifipabanilopo ati ipanilaya je ohun ti awon omo alaigboran adugbo wa ma unse",
"o se oju bi oju oloro ero inu e kun fun oro",
"Egbon oloro yen lo unbo yen o e tete palemo ko to de",
"oro inu e o ju ti akekepelu e wa tun ma se nuonuo",
"ogbon arekereke po ni owo re ako si ni gba e laye nibi yi",
"Alejo oran ni omona je",
"omo obinrin to se oju bi oju amugbo yen da won ni ibi lo wa",
"Esu ni e ma wa da ibiyi ru o a ti gbo iroyin unkan to ti se lati ehin wa",
"oro amugbo wo lo unso lenu o ro pe akomo oun ti a unse ni",
"ejo oponu wo lo unro nibe yen koja wa sibi lati se ise ti mo gbe fun e",
"Ejo oloro ni e bo se unse bi igba ti o ko le soro yen",
"oloro inu awon omo yen lo unbo yen e tete gbaradi",
"ore mi ko si lowo yin ki e ma hale momi mo",
"Akutunku e ni ona orun",
"To ba bami fa ijogbon wa ri isoro ti o ko ro tele",
"onijogbon eniyan ni gbogbo yin ninu ile yi o",
"olosho ni omoyen o ko kin se omo gidi omo lasan lo je",
"omo eru lasanlasan ni ko ja mo unkankan e se bo se wun yi",
"ajoji lo je nibi yi ma dasi oro ilu wa awon omoonile nikanlo lenu oro ",
"atowunrinwa lo je o kinse omoilu yi omo ojulowoilu lafe basoro",
"onibaje ni omorandu yi iwa ibaje tikun owo re",
"onibaje ni e a moiru yin e kinse eyan gidi e kan foju jo eniyan",
"iwa ibaje ti kun owo e ju o je fura si ara re",
"e danasunle won ki e jo gbogbo e guruguru ko ma ku unkankan",
"ma dana sun dukiya eroja ogun ti o gboju le ti koni ku ikankan",
"iwa jaginijagan ti kun owo o kin se omo jeje rara",
"ijogbon re ti poju o kin se jeje",
"iwa ibanuje ni awon to ju ado oloro yi hu si ilu won ba dukia je",
"e bawon wo ijakadi ke lu gbogbo won yannayanna e ma da enikonkan si",
"abori ma bowa o foju jo eniyan ofiwa jo eranko",
"idarudapo ti waye ninu ere idije bolu ti won gba",
"iwa iranu ati asa osi ti kun owo re",
"e ko idamu ba won ke ko jinijini bowon",
"ado oloro pawon run ni ilu gesi",
"ke paro mo eniti ko se ki won le dayin lare oro na",
"e sewon lose e ma dari jiwon",
"ma lu e ni alupa moku iwo gan a mo pe obayan ja",
"omugo alailogbon ni wo arakunrin yi o wo bi won se fi ogbon gba ti owo re",
"Oluwa gbogbo awon ajenirun oluwa pawon danu",
"kilode ti awon muslim pa awon christian bayi",
"Awon Musulumi n ba aye wa je",
"olori buruku eniyan nie o kinse eyan dada",
"alailopolo eniyan ni e ko si ogbon kankan lori e",
"ori e ope o ni lakaye kankan o kan dagba lasan ni",
"alaigbonron omo ni ko ni gboro si obi lenu tinu e nikan lo mase",
"alai ni ironu oko to fi aro muti ko moju ko se faji lo",
"iyawo olobun yide koniwe dada ara re asamo run ",
"akidanidani oponu ode",
"iwa alailopolo lo hu yen pelu bo se da gbogbo reru",
"ma yeye toba bami fa wahala iwo omode anan yi",
"oponu ni gbogbo yin ",
"eni ti o ni iru eni ko le mo iyi eni",
"Oloye rara gbogbo ikan loti emoni",
"olofo ni baba e iwo omo were yi",
"ori re daru pelu ejo oriburuku to unro yen",
"o jo asiwere ti ko loye beni ",
"onidoti ati olorun ni sisi to unbo lokan yen o kan dara loju lasan ni",
"o je okunrin asiwere ti were die ti fe si ni agbari",
"olofo alaimokan ni iwo",
"awon omugo meji unse ore won go ju isu lo",
"Jeki ogun kilasi ti ko wa tele o je asan bi iwo",
"unkan ti alaimokan e fi unse ara re lo poju",
"irin idoti lo unrin yi ma fi tire kobami",
"Omugo asiwere nikan ni iwo",
"alakoba ni ore to joko yi maje ko fi tire koba wa",
"olopolo dudu ti ko mo unkan ni eniti e ran nise",
"morope o un se aisan pupo pelu bo se unwo mi yen ",
"alailoye eniyan bi tire lope mi ni",
"baba yin were ati gbogbo ara ile yin",
"olori buruku omo",
"ologogoro ni eni ti eni kinloba lati ko unkan lowo re",
"ma gbe oko ologogoro yen wa si odo mi ko saye fun iru eni yen nibi",
"iwa alailopolo eniyan lo hu nibeyen ",
"ma fimi we alailopolo to duro tie",
"eroburuku ti kun inu okan e",
"apa ti ko mo iye owo",
"apa iyawo ti o eye owo",
"alabosi iyawo were",
"alabosi oko were",
"onisonu omo",
"onisonu ni Iwo oko yi o",
"onisonu ni Iwo iyawo yi o",
"akotileta obinirin lo fe ya",
"oloju kokoro iyawo ti koni itelorun ni e",
"oloju kokoro alai ni itelorun omo ",
"alaroye ni e ejo e tipoju",
"se kokin se alaroye ni eni ti e muwa sibi",
"okuta oshi okoni aje",
"ma ko okuta wa bami o",
"esu leyin ibeji ",
"iyawo odale o le payan",
"iyawo alaifelosiwaju oko",
"oko alaife losiwaju iyawo",
"odale ni e o kan undogbon ni",
"ole buruku alatoroje",
"amukun meko ode omo",
"olosho asewo adugbo",
"egbon alatoroje yen niyen",
"odaju oshi buruku o le payan",
"alaya galemo bi apata",
"esu ni egbon yi o",
"ori yin ti daru gidi",
"alailojuti iyawo rada rada",
"Iwo kan randu bi osa akunlebo",
"oda bi esu ti won ta epo le lori",
"abi idi gigan ",
"oda bi ibeji oran",
"elenu funpo bi agolo miliki",
"elese wogowogo bi ti pepeye",
"eleti gobi",
"alapa ma sise ole omo",
"olowo tite bi ti abirun",
"abirun ni omo ti won bi",
"aye ti polokunmosun ",
"ikan unse e",
"alariwo iyawo oshi",
"oni jagidijagan oko were",
"oni jagidijagan iyawo were",
"odabi igi agun ma dorun",
"alara gbigbona oshi",
"alara gbigbe bi igi idana",
"alai mu okan bale",
"lakiriboto obirin ti o loju ara",
"iyawo elemi esu",
"oko elemi esu",
"omo elemi esu",
"elemi kemi owo",
"emi buruku ungbe inu e",
"pastor eke to fun omo ijo loyun",
"pastor radarada tun fi owo te omu omo ijo",
"omo buruku ton fi ipa ba awon obinrin sun",
"elemikemi aje oshi",
"eru ni awon baba baba won",
"eru lasan ni ko jamo unkankan",
"eleyin bi eyin a won aje",
"oju e bi oju aje",
"golugo ode omo",
"oju burukulo fi unwo mi",
"ma foju buruku womi",
"alai ni lakaye oponu",
"omo radarada wo lode ibi",
"ma gbe radarada e de ibiyi o",
"alai ni lakaye ",
"opolo e ti yoro",
"oro alaini opolo lo unso yen",
"oni imu kulubo",
"imu bi salensa moto ",
"adigunjale ni e",
"oni gbese oko ",
"oni gbese iyawo",
"ise adigunjale lo unse",
"asewo osi",
"e pa gbogbo awon adigunjale to wa nibe",
"elenu gigun bi ibon",
"ashawo kobokobo ni obirin yen",
"oni shina iyawo",
"Oni iro nun rara ni iwo omo kunrin yi",
"aye tin see awon ebi e kokan mo ni",
"oni sokuso omo kekere",
"eleya ni iwo omo obirin yi",
"oni nu buruku omo kekere",
"iyawo elejo wewe",
"alai wulo okunrin",
"alaya galemo bi apata",
"ori e ti bu",
"ori e ti baje ",
"ori e ti te",
"ibanuje ti de ba e o",
"alai lejo okan kese boran won ni",
"alai gbeko yi",
"alai ni iroru ara kalatia",
"Were kolu e ni",
"Pastor to sa sosokuso kiri",
"Lobimo tire koto ma fomolomo so omo",
"aye e ti ta bi guguru",
"oduro bi sigidi ",
"oni di gbigbe obirin",
"osa dabi panla pelu bo se gbe",
"alara yiyi kinwe mo",
"elekanna bi ti adete",
"apari omode",
"oloshi ori bi awan abiku agba",
"alabosi oni iranu agbalagba ",
"Iyalaya iya e ",
"o da bi sibi obe",
"oju e tabi eyele ",
"olomu sisan wale",
"on dun bi ewure",
"on se balabala",
"arindin oko tun fu pata iyawo e",
"alaye didaru",
"elejo wewe",
"baba nla baba re otobe",
"iyawo eleje riru",
"oni gberaga oshi",
"Wobose tabi babalawo ",
"obo oyato si e",
"iyawo oni gbona ara",
"Iwo olowo riro ",
"alai laponle lara",
"osori kodoro bi igbako",
"Alaya fefe bi eran ori apata",
"oni kun batun batun",
"olopolo yiyoro ",
"Osenu soro bi sokoto baba suwe",
"Haaa isele nla lose ni owo ikunle abiyamo",
"kin segbe ko ole ri ile oko gbe",
"ori iya mi o mase e lese danun olori nla",
"aye yin ti daru patapata",
"oni ikun gbemgbem",
"inu ni bini oshi",
"emere buruku",
"Omode yi ki gboro ose bi ewure kiri",
"Oleri ile oko gbe toripe okun idile damu e",
"di e lo fi se were",
"ikeji aja lasan ",
"ewo oju re bi ti were",
"ose ori bi igun ile",
"dindinrin agaba lasanlasan",
"olori gigun bi ti tonlotonlo",
"Ma gbe ese osi e wo ile mi o",
"alai da buruku",
"Oni ewa lara kobo",
"oni laikaye bo se dagba to",
"ra okunrin yen sa run bi eyi tio fi ikan osun iyawo pa ara",
"enu faya ",
"wa kan idin ninu iyo",
"moti mope omo iran ki ran nie",
"ko nise ko labo",
"ko nise afi go rin kiri",
"ileyin ojo nla",
"elete pipun",
"asi ere buruku",
"eleru town councils",
"Wobose tabi babalawo ",
"alakoba ni iwo omo yi o",
"ose mi biti Malu bayi",
"obo nlakido",
"Haa omu oti ile mo",
"agba yaa ni baba e o",
"aladanikan je omo kekere",
"oni wa buruku",
"alainilari jatijati",
"Wobo se rin bi elese kan bayi",
"Wo bose run bi ako wure",
"Gbogbo ile yin lapapo ti ya were",
"Ashawo ni iya re se leko",
"oponu ara ilero omo",
"Olodo kole fi idi igo kowe rara",
"Ile bi ile were ",
"Gbogbo yin ogba dun ore yin ",
"ori gboro bi okun sokoto",
"Iyalaya baba re ni mo bawi",
"Oluju fanta elese coke",
"Omo jora re loju gbupoju",
"oda bi igi idana",
"alapa bi apa alujonu",
"Were alaso kuku niyin",
"ala ya gbigbe bi sign bodu",
"olorun gboro bi eye ogango",
"eleti kika bi ruba to mu na",
"Ti nba fun o ni gbati oni gboro mo laila",
"Se sinwi bayi ",
"elenu bi enubemirin",
"oloju bi eye owiwi",
"elemi ke mi oshi",
"Se ori yin o gbala bayi",
"Ose nu pelebe bi obe irele ",
"oni iwa ibaje",
"alara yiyi bi ti opolo",
"Wa sa ma gbo bi ti aja iya akara",
"Osema wo aso toju e lobayi oponu",
"oga yin buru gan asa ma gbo bi aja",
"Eleyin katakata bi ti katabila",
"alaso pipan bi te su",
"Awon olopa mawuwa bi ika",
"Awon iran ki ran gbogbo wo yi",
"ori bantu bi apo ewa",
"olori pipon bi oyinbo ilero",
"Ma gbe ese osi e wo ile mi o",
"elejo wewe obirin",
"elenu fife oshi",
"Abi ele yi yawere ni ",
"Oro to nso ko mu ogbon wa ",
"Ole gbewiri ",
"Omo ita ni e ni wobo se soro",
"omo ale buruku",
"Omo bosede yi o ti ni iteri ba rara",
"ewure oyato si e",
"oponu ni e apa yan nie",
"oda bi iwin inu igbo",
"oju bi oju ebora",
"elese bi ese pepeye",
"Ika lokun rin e",
"elanu gbagada bi igba wara",
"owo ni eleyi ma ntoro lojojumo komo ju owo lo",
"omo yi o ni laakaye bi o ti wu o mo ",
"won n ba e soro o un wa orun ki epe lo fe gba",
"epe ti mue wa lati ile",
"sigidi re ti se tan lati se esin lo fi ni kan gbe oun lo sodo lo we",
"wo ma to fi e se esin ti esi idanwo re ba ti jade",
"arakunrin ti o n wo lokan yen oponu aye oun orun ni",
"oponu akidandanini e",
"ti o ba ti ri eniyan to go ju e lo ki o pee lejo wipe o se gba ise re se",
"a fe e je wipe nitori ti e ni won se n pe awon eeyan kan ni a gun ma ni iye ni tori bi o se ga to lo se go to",
"wa kan soro ni igba miran bi e ni wipe o ki ronu",
"o ni ironu kankan o kan hu iwa bi ose wu e ni",
"o kan fe ya ako aja abi irin osi le sa",
"emi ko kinse ako aja o",
"Iwo ni eku eda to da gbogbo wahala yi sile alagabangebe ni e",
"tani eku eda to da gbogbo e sile",
"Lowe lowe ni a n lu ilu agidigbo ologbon lo n luu olumoran lo n jo kii se iru awon eniyan bii tire",
"akukubi ma san ju radarada ti e yii",
"omo radarada lobi omo lasan",
"dayo se o ma ro ori ara e sa",
"ole alapa ma sise ni e",
"a kuku ti mo wipe eni to daso fun ole re na ni yo ba pa laro",
"o da mi loju wipe ti a ba la ori re eko elewe la ma ba ni ibi ti o ye ki opolo re wa",
"baba ofo e fi aro yin sere e wa n wa eni ti e ma fi ikanra aye yin mo nsin",
"ibikunle ipade awon ojogbon re ti o ba kan awon omuti a ma ranse pe e",
"omuti lasanlasan ni e",
"ole alapa ma sise a fi ko se afowora",
"iwa ko jo ole ko jo afowora ti o ran baba re lo ewon naa ni iwo na tun yan laayo",
"sebi won ni bi olounje ba ri e to gbe sa ki iwo naa fi aije te lorun Bii ti Jumoke ko omo naa o mo oju depo ti yo mo ara",
"ki lo de ti o ma n huwa bi omo abi ipabe na",
"iwo omo yi o ni lakaye bi o ti wu o mo ",
"lakaye ku die kato fun e",
"won n ba e soro o un wa orun ki epe lo fe gba",
"ma se epe fun e to ba jami lole",
"sigidi re ti se tan lati se esin lo fi ni kan gbe oun lo sodo lo we",
"Iwo omo oju o ri ola ri ti n pe ara re ni ola ni iyonu ",
"iwa omo oju o ri ola ri lo unhu",
"omo ilele ni e bi won gbe e si ori ibusun o ma pada jabo gbehin na ni",
"iwo omo ilele lasanlasan",
"a fe e je wipe nitori ti e ni won se n pe awon eeyan kan ni a gun ma ni iye ni tori bi o se ga to lo se go to",
"wa kan soro ni igba miran bi e ni wipe oo kii ro inu",
"won ma n so wipe bi ile ba n toro omo ale ibe ni o I dagba Daju daju omo ale ni e",
"O kan fe ya ako aja abi irin osi le sa",
"Oun gbo ti eku to fun eye bee lo se tun n gbo ti eye to fun eku alaida eniyan ni e",
"Iwo ni eku eda to da gbogbo wahala yi sile alagabangebe ni e",
"Oro wo lo wa ni enu a se igi ta re",
"Lowe lowe ni a n lu ilu agidigbo ologbon lo n luu olumoran lo n jo kii se iru awon eniyan bii tire",
"Akukuubi ma san ju radarada ti e yii",
"o ni lakaye bi o ti wu o mo",
"dayo se o ma ro ori ara e sa",
"iwo arakunrin abi ila hara hara bi eni kiniun ba ja yi se o tun de losan yi",
"a kuku ti mo wipe eni to daso fun ole re naa ni yo baa pa laro",
"o da mi loju wipe ti a ba la ori re eko elewe la ma ba ni ibi ti o ye ki opolo re wa",
"baba ofo e fi aaro yin sere e wa n wa eni ti e ma fi ikanra aye yin mo nsin",
"ibikunle ipade awon ojogbon re ti o ba kan awon omuti a ma ranse pe e",
"bisi se ti on ba ni eran oniwo maa kan ni pa a wa je igbin e sha",
"kolade n ba so pe ko ni ye e sugbon leyin wo",
"iwa ko jo ole ko jo afowora ti o ran baba re lo ewon naa ni iwo na tun yan layo",
"sebi won ni bi olounje ba ri e to gbe sa ki iwo na fi aije te lorun bi ti jumoke ko omo na o mo oju depo ti yo mo ara",
"baba tawa ti o ri yen afofun gbemu ni",
"opolo ojo ku de ibi wipe ko le fi idi igo ko o",
"ogbon o kan ojo ori bi be ko ko ye ki o so iru oro ti o so ni ana",
"gbogbgo eeyan lo kuku mo e wipe o pa iro ju fere lo",
"agbalagba re to so yangan mo idi lo so ara re di eleya adiye",
"ibaje wipe won ko e ni ile yin ti o si gba eko I ba daa",
"se ti won ba pe ki awon bale ile jade iwo na ma ka ara re mo won",
"omo ti a ba bi ni ile ire o gbodo maa hu iru iwa to ma n hu ",
"iwo amunibuni eran Ibiye ti Ibiye fo oju otun eran re fo ti osi",
"iwa amunibuni lo hun yen o ronu ko to se",
"mi o ro pe ile ire ni won tibi e",
"olosi ma fi tire koba emi laro kutukutu yi",
"iwo lo fi tire koba mi",
"gbogbo eniyan n raun wipe oja o ta waara iwo na n soro oja wo ni asewo re n ta o",
"o ti ya obun ju ninu iwo ati elede olorun nikan lo mo eyi to mo ju",
"ebolo ni e ko si fi a se le se e ki o ma run igbe",
"a ki danidani ni dafidi a fi bi eni wipe omu ewure lo mu dagba",
"enu anike ti le jo ju Emi o ri iru olofofo bii ti e ri",
"olofofo ni iwo ati gbogbo awon ore re",
"ki lo de ti o ma n huwa bi omo abi ipabe na",
"iwo omo yi o ni lakaye bi o ti wu o mo ",
"se ti won ko ba bi e o o ni wa saye ni",
"won n ba e soro o un wa orun ki ete lo fe gba",
"ojo esin re to su o fe ro die o ku",
"sigidi re ti se tan lati se esin lo fi ni kan gbe oun lo sodo lo we",
"iwo omo oju o ri ola ri ti n pe ara re ni ola ni iyonu ",
"arakunrin ti o n wo lookan yen oponu aye oun orun ni",
"omo ilele ni e bi won gbe e si ori ibusun o ma pada jabo gbehin na ni",
"wo bo se unse bi agunmaniye ",
"a fe je wipe nitori ti e ni won se n pe awon eyan kan ni agunmaniye ni tori bi o se ga to lo se go to",
"wa kan soro ni igba miran bi e ni wipe oo kii ro inu",
"won ma n so wipe bi ile ba n toro omo ale ibe ni o I dagba dajudaju omo ale ni e",
"o kan fe ya ako aja abi irin osi le sa",
"oun gbo ti eku to fun eye bee lo se tun n gbo ti eye to fun eku alaida eniyan ni e",
"iwo ni eku eda to da gbogbo wahala yi sile alagabangebe ni e",
"oro wo lo wa ni enu a se igi ta re",
"lowe lowe ni a n lu ilu agidigbo ologbon lo n luu olumoran lo n jo kii se iru awon eniyan bii tire",
"akukubi ma san ju radarada ti e yi",
"o ni laakaye bi o ti wu o mo",
"dayo se o ma ro ori ara e sa",
"iwo arakunrin abi ila hara hara bi eni kiniun ba ja yi se o tun de losan yi",
"akuku ti mo wipe eni to daso fun ole re naa ni yo baa pa laro",
"o da mi loju wipe ti a ba la ori re eko elewe la ma ba ni ibi ti o ye ki opolo re wa",
"baba ofo e fi aaro yin sere e wa n wa eni ti e ma fi ikanra aye yin mo nsin",
"Ibikunle ipade awon ojogbon ree ti o ba kan awon omuti a ma ranse pe e",
"bisi se ti on ba ni eran oniwo maa kan ni pa a wa je igbin e sha",
"kolade n ba so pe ko ni ye e sugbon leyin wo",
"iwa ko jo ole ko jo afowora ti o ran baba re lo ewon na ni iwo na tun yan layo",
"sebi won ni bi olounje ba ri e to gbe sa ki iwo naa fi aije te lorun Bii ti Jumoke ko omo naa o mo oju depo ti yo mo ara",
"baba tawa ti o ri yen afofun gbemu ni",
"opolo Ojo ku de ibi wipe ko le fi idi igo ko O",
"ogbon o kan ojo ori bi be ko ko ye ki o so iru oro ti o so ni ana",
"gbogbgo eeyan lo kuku mo e wipe o pa iro ju fere lo",
"agbalagba re to so yangan mo idi lo so ara re di eleya adiye",
"i ba je wipe won ko e ni ile yin ti o si gba eko I ba daa",
"se ti won ba pe ki awon baale ile jade iwo na ma ka ara re mo won",
"omo ti a ba bi ni ile ire o gbodo maa hu iru iwa to ma n hu ",
"iwo amunibuni eran Ibiye ti Ibiye fo oju otun eran ye fo ti osi",
"o wulo fun nkankan bi o tile wu ki o mo",
"bawo ni owo se da emi ati oloriburuku bii tie yi po",
"olosi ma fi ti re ko ba emi laaro kutukutu yi",
"lati ojo ti mo ti daye mi o ri eniyan to ya omugo bi ti Damilola yi ri sa",
"gbogbo eniyan n raun wipe oja o ta waara iwo na n soro oja wo ni asewo re n ta o",
"o ti ya obun ju ninu iwo ati elede olorun nikan lo mo eyi to mo ju",
"ebolo ni e ko si fi a se le se e ki o ma run igbe",
"aki danidani ni dafidi a fi bi eni wipe omu ewure lo mu dagba",
"enu anike ti le jo ju Emi o ri iru olofofo bii ti e ri",
"olofofo ni iwo ati gbogbo awon ore re",
"lati ori iwo de ori baba re ole ni gbogbo yin ni idile yin",
"iwa abosi ti o n hu naa ni ko je ki aye re o ni itumo",
"nje o ti ri ibi ti ai ni itelorun gbe e de",
"ai fini peni ai feeyan peyan lo mu ki ara oko bi tie o san bante wolu",
"ti a ba mu ni mini meji mi o lero wipe a ma le ka eeyan meta to ponu ju e lo ni inu ilu yi",
"nda re ni yoo kuku pada pe ara re leru",
"kolade mo fi titobi anobi be e ma ko ori buruku re ran wa",
"igba ti tie ti jona tan o wa n wa eni ti o ma ba ko ina mo tie",
"ireti aye re ti baje koja ilaji",
"ehana ponbele ni iwo omo yi inu igbo lo ye ko ma gbe pelu awon ikoko",
"kokoro a jeni run ni awon mejeji",
"o kii se eniyan to see fi okan tan",
"eniyan ni tola naa ti ile ba da",
"mo lero wipe oti ti o ma n mu ti da e lori ru",
"ole ni kolapo owo re o ran tete",
"ojo gbogbo ni ti ole re sugbon ojo kan soso ti o je ti oniikan ti pe loni",
"ti eniyan ba n toto omo lowo eledua o ye ko maa ranti lati so wipe oun o fe iru omo bi tie yi o",
"olote ni gbogbo yin o ju de si ma ti yin gbeyin ni",
"eri bo ti ri kunta bi sigidi ori esu",
"gbogbo yin ni ile yin le dudu bi eyin ikoko",
"opolo re o yato si ti aayan pelu awon oro to n jade lenu re yi",
"sebi omo eni o ba joni a ba yo emi o mo bi olopolo pipe bii Dele se bi iru iwo yi",
"Igba wo lo da olugbaninimoran fun eto igbeyawo iwo ti oo ri ile oko gbe",
"alai more ni iwo arakunrin yi",
"o kii se eniyan gidi bi beeko o ko ba ti gbiyanju lati gba ije lenu ore re",
"obayeje ni arabinrin yi",
"sade afi igba to ya omo irole aye sha",
"ti a ba fi omo we omo a ma na iru re yi pa ni",
"o mo ju ounje lo won fi se e ni",
"gbogbo okunrin to ba kan enu si e ni iwo n ba lo lai se aja",
"iyawo gbenga yen asoro so boto ni",
"gbogbo eniyan lo kuku mo wipe o san la ti so asiri ara eni ni gbangba oju ju lati so fun e ni koro yara",
"o go o fi enu ho ara",
"won ma n so wipe eniyan go bi owo osi sugbon iwo go ju owo osi lo",
"ase eniyan rada rada aye oun orun ni e",
"o kii se eni iyi",
"oniranu bii tie nikan na lo le so be",
"o kan ya afofun gbe mu",
"wo ti yara e se ri o ti ya onidoti ju",
"se o ri ounje ri ni o kan n huwa bi elebi",
"se baba lo yanu gbaga bi idi adiye to n soro si bayen",
"o ma n huwa bi eni ti won fi owo to",
"arungun ni eyin omo meteta yi ",
"gbe enu rirun e dake jare ta lo pe e soro",
"esin ti ba aye yin je",
"gbogbo n to ye ki o fi gbon lo ti fi ga tan",
"o se ni laanu wipe mo sese mo pe ogboju ole ni e",
"ole a lapa ma sise ni e",
"a ri je ni idi idaru ni Bolanle",
"onisekuse ni Bolu ati Biola",
"okanjuwa oni wobia ni ogbeni rasheed yen",
"Ki lo de ti o ma n huwa bi omo abi ipabe na",
"Iwo omo yi oo ni laakaye bi o ti wu o mo ",
"Se ti won ko ba bi e o o ni wa saye ni",
"won n ba e soro o un wa orun ki ete lo fe gba",
"ojio esin re to su o fee ro Die o ku",
"sigidi re ti se tan lati se esin lo fi ni kan gbe oun lo sodo lo we",
"iwo omo oju o ri ola ri ti n pe ara re ni ola ni iyonu ",
"arakunrin ti o n wo lookan yen oponu aye oun orun ni",
"omo ile nle ni e bi won gbe e si ori ibusun o ma pada jabo gbehin naa ni",
"ti o ba ti ri eniyan to go ju e lo ki o pee lejo wipe o se gba ise re se",
"a fe e je wipe nitori ti e ni won se n pe awon eeyan kan ni a gun ma ni iye ni tori bi o se ga to lo se go to",
"wa kan soro ni igba miran bi e ni wipe o ki ro inu",
"won ma n so wipe bi ile ba n toro omo ale ibe ni o I dagba Daju daju omo ale ni e",
"o kan fe ya ako aja abi irin osi le sa",
"oun gbo ti eku to fun eye bee lo se tun n gbo ti eye to fun eku alaida eniyan ni e",
"iwo ni eku eda to da gbogbo wahala yi sile alagabangebe ni e",
"oro wo lo wa ni enu a se igi ta re",
"lowe lowe ni a n lu ilu agidigbo ologbon lo n luu olumoran lo n jo kii se iru awon eniyan bii tire",
"akukuubi ma san ju radarada ti e yii",
"o ni laakaye bi o ti wu o mo",
"dayo se o ma ro ori ara e sa",
"iwo arakunrin abi ila hara hara bi eni kiniun ba ja yi se o tun de losan yi",
"a kuku ti mo wipe eni to daso fun ole re naa ni yo baa pa laro",
"o da mi loju wipe ti a ba la ori re eko elewe la ma ba ni ibi ti o ye ki opolo re wa",
"baba ofo e fi aaro yin sere e wa n wa eni ti e ma fi ikanra aye yin mo nsin",
"ibikunle ipade awon ojogbon ree ti o ba kan awon omuti a ma ranse pe e",
"bisi se ti on ba ni eran oniwo maa kan ni pa a wa je igbin e sha",
"kolade n ba so pe ko ni ye e sugbon leyin wo",
"iwa ko jo ole ko jo afowora ti o ran baba re lo ewon naa ni iwo na tun yan laayo",
"sebi won ni bi olounje ba ri e to gbe sa ki iwo naa fi aije te lorun Bii ti Jumoke ko omo naa o mo oju depo ti yo mo ara",
"baba Tawa ti o ri yen afofun gbemu ni",
"opolo Ojo ku de ibi wipe ko le fi idi igo ko O",
"ogbon o kan ojo ori bi be ko ko ye ki o so iru oro ti o so ni ana",
"gbogbgo eniyan lo kuku mo e wipe o pa iro ju fere lo",
"agbalagba re to so yangan mo idi lo so ara re di eleya adiye",
"iba je wipe won ko e ni ile yin ti o si gba eko I ba daa",
"se ti won ba pe ki awon baale ile jade iwo na ma ka ara re mo won",
"omo ti a ba bi ni ile ire o gbodo maa hu iru iwa to ma n hu ",
"iwo amunibuni eran Ibiye ti Ibiye fo oju otun eran ye fo ti osi",
"o wulo fun nkankan bi o tile wu ki o mo",
"bawo ni owo se da emi ati oloriburuku bii tie yi po",
"olosi ma fi ti re ko ba emi laaro kutukutu yi",
"lati ojo ti mo ti daye mi o ri eniyan to ya omugo bi ti Damilola yi ri sa",
"gbogbo eniyan n raun wipe oja o ta waara iwo na n soro Oja wo ni asewo re n ta o",
"o ti ya obun ju Ninu iwo ati elede Olorun nikan lo mo eyi to mo ju",
"ebolo ni e ko si fi a se le se e ki o ma run igbe",
"a ki danidani ni Dafidi A fi bi eni wipe omu ewure lo mu dagba",
"enu anike ti le jo ju Emi o ri iru olofofo bii ti e ri",
"olofofo ni iwo ati gbogbo awon ore re",
"lati ori iwo de ori baba re ole ni gbogbo yin ni idile yin",
"iwa abosi ti o n hu naa ni ko je ki aye re o ni itumo",
"unje o ti ri ibi ti ai ni itelorun gbe e de",
"aifini peni ai feeyan peyan lo mu ki ara oko bi tie o san bante wolu",
"ti a ba mu ni mini meji mi o lero wipe a ma le ka eeyan meta to ponu ju e lo ni inu ilu yi",
"nda re ni yoo kuku pada pe ara re leru",
"kolade mo fi titobi anobi be e ma ko ori buruku re ran wa",
"igba ti tie ti jona tan o wa n wa eni ti o ma ba ko ina mo tie",
"ireti aye re ti baje koja ilaji",
"Ehana ponbele ni iwo omo yi inu igbo lo ye ko ma gbe pelu awon ikoko",
"kokoro a jeni run ni awon mejeji",
"o kii se eniyan to see fi okan tan",
"eniyan ni Tola naa ti ile ba da",
"mo lero wipe oti ti o ma n mu ti da e lori ru",
"ole ni Kolapo owo re o ran tete",
"ojo gbogbo ni ti ole re sugbon ojo kan soso ti o je ti oniikan ti pe loni",
"ti eniyan ba n toto omo lowo eledua o ye ko maa ranti lati so wipe oun o fe iru omo bi tie yi o",
"olote ni gbogbo yin o ju de si ma ti yin gbeyin ni",
"e ri bo ti ri kunta bi sigidi ori esu",
"gbogbo yin ni ile yin le dudu bi eyin ikoko",
"opolo re o yato si ti aayan pelu awon oro to n jade lenu re yi",
"sebi omo eni o ba joni a ba yo emi o mo bi olopolo pipe bii Dele se bi iru iwo yi",
"igba wo lo da olugbaninimoran fun eto igbeyawo iwo ti oo ri ile oko gbe",
"alai moore ni iwo arakunrin yi",
"o kii se eniyan gidi bi beeko o ko ba ti gbiyanju lati gba ije lenu ore re",
"obayeje ni arabinrin yi",
"sade afi igba to ya omo irole aye sha",
"ti a ba fi omo we omo a ma na iru re yi pa ni",
"o mo ju ounje lo won fi se e ni",
"gbogbo okunrin to ba kan enu si e ni iwo n ba lo lai se aja",
"iyawo gbenga yen asoro so boto ni",
"gbogbo eniyan lo kuku mo wipe o san la ti so asiri ara eni ni gbangba oju ju lati so fun e ni koro yara",
"ogo o fi enu ho ara",
"won ma n so wipe eniyan go bi owo osi sugbon iwo go ju owo osi lo",
"ase eniyan rada rada aye oun orun ni e",
"o kii se eni iyi",
"oniranu bii tie nikan na lo le so be",
"o kan ya afofun gbe mu",
"wo ti yara e se ri o ti ya onidoti ju",
"se oo ri ounje ri ni o kan n huwa bi elebi",
"es baba lo yanu gbaga bi idi adiye to n soro si bayen",
"o ma n huwa bi eni ti won fi owo to",
"arungun ni eyin omo meteta yi ",
"gbe enu rirun e dake jare ta lo pe e soro",
"esin ti ba aye yin je",
"gbogbo ohun to ye ki o fi gbon lo ti fi ga tan",
"o se ni laanu wipe mo sese mo pe ogboju ole ni e",
"ole a lapa ma sise ni e",
"a ri je ni idi idaru ni Bolanle",
"onisekuse ni Bolu ati Biola",
"okanjuwa oni wobia ni ogbeni Rasheed yen",
"o da bi eni wipe ole jija ni ise idile yin",
"Ki la maa ri ti o tie so oro to mu opolo wa leni",
"gbewiri ni ebun kan soso ti mo mo wipe Ayinde ni",
"ati Ibidun ati Kadija awon mejeji pa iro ju fere lo",
"Iba je wipe won se idije lati yon eniyan to ponu ju ninu aba wa wi o dami loju wipe iwo lo ma gbe ife naa",
"akebaje ni e",
"anu awon eniyan to ri e bi agba to le gba won ni imoran lo kan se mi",
"bi ki ba n se wipe o ya ole alapa ma sise ki lo de to joko sile laaro kutu ojo aje",
"gbogbo eeyan n soro iwo ti oo mo ona ile baba re naa n da si oro ilu",
"ki lo de to ya aladanikanje bayi na",
"ko ye ki awon obayeje bii tie o maa ba omo eniyan gbe laarin ilu",
"to ba wo igbesi aye Hakeem wa mo wipe ni tooto bibire o see fowo ra",
"ajegbodo re n weni kunra ni",
"dakun fi omo mi lorun sile ma so mi di da bi mo se da",
"Inu baba re naa yo si maa dun wipe oun ti bimo bayi o",
"won n pe awon arewa obirin iwo na n nawo",
"Iya re o si ni mo wipe se ni oun fidi jona lori re bayi o",
"awon baba atoku ma ku a mo ona orun mo lo kan lo so be",
"Ikan o gbe kan owu janto ni oro gbogbo awon omo re",
"se werediran loruko ebi yin ni",
"adojutini ni iwo ati iya re",
"won ni pe omo Shola jale owu ija gbon ni omo kuku ran",
"oloju kan naa ni yoo joba ni ilu awon afoju bi bee ko oo le je olori",
"o dele olounje debiti aya ni titi",
"iya re ni ako aja",
"oniregbe ni badamosi",
"elenu rirun bi akitan",
"ati igba ti Fisayo ti wole ni gbogbo yara yi ti n run",
"iba je wipe o ma n lo opolo e oo ba mo pe ko ye ko se be",
"nje iwo yii tie ma n ronu ko to soro rara sa",
"omuti gbagbe ise ni tantolorun",
"gbogbo eniyan niwo lero wipe o ya ole bi tie",
"iwa igbaya lo hu leekan yen",
"alai loju ti ni gbogbo yin",
"iwo adojutini omo tin ku nijo sunna",
"bi iresi pakuta se enu atoroje e lo ye ka ti gbo",
"eyin niyen bi ti asin",
"eyinju kongba bi ti opolo",
"gbogbo awon ti mo mo to n je Kolade ni won ni lari afi iwo",
"asise lo je fun awon obii re",
"omo langidi o wa san ju iru iwo yi sa",
"waa kan maa huwa bi eni epe n ja",
"Ko si nkan ti iwa e fi yato si ti eranko",
"Iba je pe o wulo ni nba mu e lo",
"o ni aponle fun ara re bo ti wu o mo",
"kani pe a le ti oju mo alaida eniyan o ba ti ri enikeni ba rin",
"o je nle oro je nile egungun ni e",
"elenu meji ni gbogbo won e ma gbeke le won",
"won o see fi okan tan eletan ni won",
"ote ti ba gbogbo yin je",
"eletan niiwo omo okunrin yi",
"alaida eniyan ni e iwa buruku kun owo re",
"ohun to buru ni pe ke ni apa ariwa gege bi kristeni kan ti n sare mate si tinubu",
"omugo ni o won ti gba towo pelu ogbon",
"apc je egbe esu ati egbe satani",
"da fifo oro olukoni catholic ko le jade ki lo mu ka kari so gba fun",
"alakori se unkan to fe so na niyen ",
"emi kokinse alakori eniyan dada ni mi o",
"olopolo kukuru alainironu loje ",
"ti o ba fa wahala pelu mi ma je oju e",
"ma je oju e ti o ba se were pelu mi",
"omo idamu adugbo yen lo unbo yen",
"idamu eniyan to undale ru",
"iru agbako eyan wo ni eleyi",
"ki olorun ma je ki a pade agbako bi tie se pataki adura",
"timo ba pari pelu e wa moo pade agbako ",
"iranu ni gbogbo unkan ti o kojo",
"e wo oniranu osi ti o unbaka",
"olosa paraku nie o feran ole jija",
"gbewiri omo de kie palemo awon unkan yin",
"ki awon olopa pa gbogbo awon olosa ti o wa ni adogbo yi",
"iwa omo ibaje lo unhu yi ko ye ki a ba iru iwa yi ni owo re",
"ibaje re ko legbe o ye ki o fura si ara e",
"jibiti lo unlu kakiri o ko nise lowo",
"egbon to lu jibiti ni adugbo wa ni",
"amugbo lasanlasan o je unkankan",
"oju e bi oju amugbo",
"omugo aye ati orun lo je",
"gbajue le lo fun ke to gba ti owo e",
"e gbajue ke gba towo e",
"esi ibo yen ko niyen won ti lo gbajue fun egbe oselu keji",
"iregbe ti poju ni odo e",
"mi o raye gbogbo iregbe ti o unse",
"So fun awon eniyan asiwere ti n ja ara won bi ohanze kini idi ti ikolu ti ko wulo lori eniyan ti tinubu",
"oti lile tomu lo unpa e lomu e wu iwa beyen",
"toba ti mu oti lile oju re a ma tanna ",
"mako irewesi okan bami ",
"iwo lo muirewesi ba egbe ko ri be tele ki o to de",
"orun apadi lo unlopelu oro enu e",
"o le lo si orun apadi pelu igbagbo re bi o kobani ife",
"iwo omo arugbo yi se emilounbawi",
"se arugbo togbe sile ni yi to pe ni iyawo",
"Da gbogbo oro isokuso yii duro",
"ema bami so isokuso iyen ko kanmi",
"isokuso e ti poju ni igba gbogbo",
"madaru lo ma se bi o se unse yen",
"Ko ya mi lenu nitori awon obi re se asiwere ",
"iwa madaru lohu o todada rara",
"itanje ti poju ko si otito kan ni enu e",
"eletan ni e okan paro funmi ni",
"mi o ni itanje lowo otito inu ni mo unlo pelu re",
"arufin ni iwo omo okunrin yi",
"odaran paraku loje ki eyan sa fun e ni o",
"emi o kinse arufin bi tire o ",
"oga odaran yi ti pada de lati irinajo",
"onibaje ni iwo omode yi iwa ibaje ti kun owo re",
"ika ni olopa yen wo bi osepa omokurin yen",
"oti kan agbako lowo iya yen sa",
"ika oloju rangandan omo kekere",
"agbako gba ni eni ti mo pade lana",
"oti se ika ju wobi ose nranju mo omo yen",
"ta lo gbe agbako oga yi wa si ilese wa ",
"asiwere gba ni iwo omobirin yi",
"onisekuse agbalagba ti komo iwon ara re",
"awon olosi rederede ti won bami gbe ni adugbo wa",
"mamu ore alabosi yen wa kimi ni ile",
"oni gbese gbaraku ni yin ",
"se eya were sa abi ikan damu ori yin ni",
"aye yi osini daa eyin oniwa buruku yi",
"eyin iran kiran olote gbogbo yi",
"omo irankiran to daleru",
"iwakiwa kun owo e ju ti aburo re",
"olodo o ko le salaye arare daradara kini idi ti o fi bere lowo wa nipa awon si odo re ki o bere lowo re",
"omo irankiran ti ko leniyan nilu",
"o ti feran isekuse ju ni o fi lowo lowo",
"wobia onijekuje ni e o ko ni ajeseku",
"iwa wobia lo hu yen o tie je ounje kankan ku",
"wobia wobiliki oga ni won gbede",
"onikokuko olodo ni omo yen ko mo iwe rara",
"odale lo je mo ti mo lati ojo toti pe",
"ore odale ye ni yi e wo oju e dada",
"wa jiya to ba fi owo kanmi",
"oloju ko ngba ya lona fun mi",
"were ti joba lokan eni yi o",
"kosi aseyori kankanlati igba ti o ti bere",
"alabasepo ko si gbogbo eniyan ti o ni aseyori",
"ebi eko ose ori pipa ni be yen ",
"iya ma je toba fowo kanmi",
"ki won gba omo yen lowo omobirin yen osa se ka kiri",
"asi were olosi lo gbe mi ni",
"abi kofe da fun baba nla baba re ni",
"ki lo ko wo to lo n wo bata asiwere",
"aye e fe ta si wewe ni",
"oni irinkurin ile se pasi paro",
"lo fo enu yin e elenu runrun",
"oni gberaga osi",
"o ko jo eniyan rara eranko inu igbo lo jo",
"mi o fe ri e ni ile mi mo iwo ole yii",
"ki ni o tun wa iwo alai ni itelorun",
"awon eni omo na ko nilari",
"iwo omo ti o nilari yii",
"ki ni o n se ni beyen Iwo alaigbadun yii",
"omo pelebe bi obe yen ti lenuju",
"gbe oro isokuso re lo siwaju",
"onisokuso ni omo pelebe yen",
"gbogbo ile won yawere pata",
"ko si enikeni ti o unse imototo ni agbegbe yi ni gbogbo re se doti",
"iwa onidoti lo hu yen o ye ki o ma se imototo",
"iwo omo onidoti mawa sile wa o",
"iwa e ko yato si ti elede wo bo se ri onidoti",
"ma ro mi lejo elejo wewe",
"obo lankido maje okede bi obo ki ri adugbo",
"se oma siwin koto ma seju were ki ri",
"nibo ni pata re wa asiwere",
"wo bi o se njeun bi elede",
"se Iwo ko ri mi ni iwo were eranko yi",
"nibo ni esi idanwo re wa iwo olodo yii",
"e wo awon asiwere meji to unbo lokan",
"o kogbodo hu iwa imotaraeninikan nibi ise ",
"imotaraeninikan ti poju fun e ",
"kilode ti o fi n wo mi ole osi",
"o je nkankan bikose asiwere",
"o ti je oye alarinka to fi ese da igboro ru",
"da rerin e oniranu",
"kini o n pa e lerin alabosi",
"ma pa ariwo mo iwo omo jatijati",
"oniranu lo je a o mo koko unkan ti ohun se ",
"alabosi ni o kan se ore oju ni",
"ko si nkan ti wa si abinu osi",
"o tete ka iwe alaini Ise",
"nibo ni o ti n bo alarinka",
"pa enu re mo elejowewe",
"olodo ni e o mo unkankan ",
"lo se assignment re olodo osi",
"lo we jo obun olorun",
"fun broda e jor agbaaya",
"O ko le ki eniyan onibaje",
"oloju kokoro ni e o ni itelorun",
"te awon botini pupa oponu",
"oponu agba alainironu",
"nigbagbogbo ni oma hun hu iwa oloju kokoro",
"o le fo eyin re agba iya",
"o n huwa bi eranko ti ko ni opolo",
"emi ko nilo iranlowo re asiwere nla",
"eranko ni a won musulumi ",
"a o fe musulumi ni ele wa eniyan buruku ni wa",
"agba iya ni e o mo iwon ara e",
"alai loju ti onigbese",
"ko le yo ni kun gbesi",
"obun eranko ikeji aja",
"wo ti mo pe ni eyan a se eranko ni e",
"alai mo ore alai lope",
"ika oninu kikan",
"ko le ji ko ki oko e oni wa ibaje",
"oniwa buruku bi ti eye adan",
"koni ise a fi ko mu ogogoro",
"alailoto alaso pipon",
"abure eleyin kata kata",
"oloriburuku alai mo ejo ro alawon lilo",
"onidi bantu bi apo ewa",
"ko ri ara bo mo ori loku to n bo oniranu",
"elenu tinrin bi enu asin",
"o se enu fi fe oniranu",
"moto lo ma pa e danu Iwo ti o wulo yii",
"o ri bi o ti n soro bi baba e ode",
"ole ti o sise alara riro osi",
"afi ki a tete pa ile mo gbe wiri lode yii",
"ile to n to ro omo ale ibe ni o ti dagba Iwo omo ale osi yii",
"omo gbe wiri ni omo to unboyen",
"owu lo a fi agidi osi iwure buruku",
"se ko kin su e ni Iwo odoko buruku yii",
"Iwo omo ilenle tan panel osi",
"ko fine osi oju bi ti ebora inu igbo",
"o ri ese doro doro bi ti pepeye",
"ole olowo si le kun fun ole",
"o ri nka osu e bi ti gbo ",
"o ri rutu aboko ko alabe gijona",
"elejo were olobun oshi a fi ko ro ejo",
"gbo gbo ejo ni gije oloju kokoro ",
"ko mo ina da a fi ko ro ejo ode ",
"ode oko ko le sise a fi ko gba tete",
"ode ari obinrin yo di ",
"ko le mo owo o nje kala afi ko yan ale dindinrin buruku",
"Iwo oponu ayerada ti o le ko ile",
"o ri re agun mo de orun elese gboro ",
"se iwo lo unpe omo ni abiku agba",
"ko se ni ti o bu elenu gigun abi enu asa",
"oloshi ori bi awon abiku agba",
"elese osi kilo unbaka alafefeyeye ni egbon yo",
"elemi buruku ni eni ti o wole nisin",
"elemikemi bi tire ko le wo ibi "
        ];
        return $hate_words;
    }
}
